### ISSUE TITLE
请问下一步的计划是什么

### ISSUE THREAD

**Issue by hanyou** [zer0Black/zer0MQTTServer#2]
现在这个产品有没有正式的项目验证，你们下一步的计划是什么？

**Comment by zer0Black** [comment]
您好，说实话，这个东西就是为了熟悉mqtt写着玩的，没有特别的目的。
我本来打算继续添加各种IM的功能，好友管理，群组管理这样的功能。但是现在想把这个项目先往分布式架构改进，再考虑其他东西。
不知道您有没有什么好的建议。
