### ISSUE TITLE
关于mqtt协议编解码问题？

### ISSUE THREAD

**Issue by yeyuezhishou** [zer0Black/zer0MQTTServer#5]
netty框架中，已经集成了 new MqttDecoder()和new MqttDecoder()，为什么要自己再写一套？有什么用意吗？

**Comment by zer0Black** [comment]
是这样的，netty的确有了mqtt协议的解析，我写第二版的时候，也参考过netty的代码。没用new MqttDecoder()和new MqttDecoder()，是因为我对mqtt的理解和netty对mqtt的理解稍有不同，在协议的实现上有些小地方不太一致。
第二就是我打算在直接拓展协议层面。在mqtt的基础上添加安全协议。
