### ISSUE TITLE
当payload消息体clientId为null时候问题？

### ISSUE THREAD

**Issue by yeyuezhishou** [zer0Black/zer0MQTTServer#6]
当payload消息体clientId判断为null的时候，不是因该直接mqttConnAckMessage消息应答返回
CONNECTION_REFUSED_IDENTIFIER_REJECTED吗？
为什么看你的代码中，会要再拿cleanSession判断，cleanSession为true时，人为的往消息里面设置一个随机的ClientId
然道在客户端和服务端连接的时候，业务允许ClientId为空吗？这里有点疑惑

**Comment by zer0Black** [comment]
我记得这是mqtt协议3.1 和 mqtt3.1.1的一个区别吧。3.1.1支持客户端不传clienID，由服务端生成clientID。不过3.1没有提到这部分。
如果您看的协议是3.1的话，可能会没有这部分内容
