### ISSUE TITLE
确定换成netty5了?

### ISSUE THREAD

**Issue by jkxqj** [zer0Black/zer0MQTTServer#9]
我看netty官网最新才4.X啊。。。另外之前AIO不好吗？开源中国还有个t-io据说性能很强，方便加qq交流吗？

**Comment by zer0Black** [comment]
兄弟，这是一件悲催的事情。netty5被废弃了，由于原因据说是里面的某些模型有些问题。所以在推出一段时间后被废弃了。下个版本直接删netty6了估计。

**Comment by jkxqj** [comment]
https://github.com/jkxqj/JIM  这是我之前的项目，后端用的tomcat自带的websocket包性能很差，最近想抽时间换下，看到你这个项目不错想整合进来，方便加q交流下吗？
